version: '3.8'

services:
  app:
    container_name: backend-usuarios
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - usuarios-network

  db:
    image: postgres:15-alpine
    container_name: db-usuarios
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    networks:
      - usuarios-network

networks:
  usuarios-network:
    driver: bridge

volumes:
  db-data: